CREATE TABLE INT_METADATA_STORE (
    METADATA_KEY   VARCHAR2(255 CHAR) NOT NULL,
    METADATA_VALUE VARCHAR2(4000 CHAR) NOT NULL,
    REGION         VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT INT_METADATA_STORE_PK PRIMARY KEY (METADATA_KEY, REGION)
);
